const SET_CATEGORY = 'SET_CATEGORY';
const GET_NEWS = 'GET_NEWS';
const SEARCH_NEWS = 'SEARCH_NEWS';
const SET_COUNTRY = 'SET_COUNTRY';
const SET_NIGHTMODE = 'SET_NIGHTMODE'

export {
    SET_CATEGORY,
    GET_NEWS,
    SEARCH_NEWS,
    SET_COUNTRY,
    SET_NIGHTMODE
}